name: C++ CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y clang valgrind

    - name: Compile and run the program
      run: |
        clang++ -o hello main.cpp
        ./hello

    - name: Run Valgrind for leak check
      run: valgrind --leak-check=full ./hello
    
